### ISSUE TITLE
Added items aren't visible to others and disappear on refresh

### ISSUE THREAD

**Issue by williammartin** [davidje13/Refacto#33]
## Description

This might be related to https://github.com/davidje13/Refacto/issues/3

A couple of times now, our team has noticed that items they have added to the board are not visible to others. When they refresh their page, they need to log in again and the items are gone.

### Desired Outcome

Ideally, these items would appear for everyone as expected. However, a second option that would get most of the value would be for the page to prevent and indicate why items cannot be added at this time.

Cheers!

**Comment by davidje13** [comment]
Yep, you're correct that this is a consequence of losing the websocket connection, and there's currently no indication when that happens.

It's on my radar, and I've recently updated [json-immutability-helper](https://github.com/davidje13/json-immutability-helper/) to make it possible to create idempotent actions, which should open the door to naïvely reconnecting and re-sending any un-synced changes when the network is restored.

Step 2 will be to update Refacto to use idempotent actions for item creation, which I'm just getting to now.

Step 3 will be to update [shared-reducer-frontend](https://github.com/davidje13/shared-reducer-frontend) to automatically reconnect (or expose a hook to do this externally), and ideally expose a hook so Refacto can show some visual indication when the network connection is lost.

This is a longstanding issue but I'm hopeful it will soon be resolved!

**Comment by davidje13** [comment]
This is now (finally) resolved! The client will automatically attempt to reconnect if it loses connection. You should see a message at the top of the screen if this happens.

There's still some open stuff around refreshing tokens / signing back in, so this will get stuck if the authentication token has expired, but as long as the page hasn't been left open for several days, it should be able to reconnect automatically (and anything you do while offline will be sent when it reconnects).

Let me know if you see any issues.
